[0m19:02:14.467104 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017AA4D60730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017AA6F2FC40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017AA6F2D570>]}


============================== 19:02:14.474713 | f8a09795-cccc-4215-b280-3fe24a1f9d90 ==============================
[0m19:02:14.474713 [info ] [MainThread]: Running with dbt=1.10.11
[0m19:02:14.479244 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt docs generate', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_cache_events': 'False', 'use_experimental_parser': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'static_parser': 'True', 'write_json': 'True'}
[0m19:02:14.482215 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\projects\Hospital Readmission Analytics\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:02:14.485039 [debug] [MainThread]: Command `dbt docs generate` failed at 19:02:14.484009 after 0.26 seconds
[0m19:02:14.486100 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017AA4D60730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017AA6F2FDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017AA6F2FC40>]}
[0m19:02:14.487366 [debug] [MainThread]: Flushing usage events
[0m19:02:16.387566 [debug] [MainThread]: An error was encountered while trying to flush usage events
